import { Country } from "../types/country_type";

export const Countries: Country[] = [
    { countryId: "AF", countryName: "Afghanistan", countryCode: "+93", regex: "^\\d{9}$" },
    { countryId: "AL", countryName: "Albania", countryCode: "+355", regex: "^\\d{9}$" },
    { countryId: "DZ", countryName: "Algeria", countryCode: "+213", regex: "^\\d{9}$" },
    { countryId: "AD", countryName: "Andorra", countryCode: "+376", regex: "^\\d{6}$" },
    { countryId: "AO", countryName: "Angola", countryCode: "+244", regex: "^\\d{9}$" },
    { countryId: "AR", countryName: "Argentina", countryCode: "+54", regex: "^\\d{10}$" },
    { countryId: "AM", countryName: "Armenia", countryCode: "+374", regex: "^\\d{8}$" },
    { countryId: "AU", countryName: "Australia", countryCode: "+61", regex: "^\\d{9}$" },
    { countryId: "AT", countryName: "Austria", countryCode: "+43", regex: "^\\d{10}$" },
    { countryId: "BD", countryName: "Bangladesh", countryCode: "+880", regex: "^\\d{10}$" },
    { countryId: "BE", countryName: "Belgium", countryCode: "+32", regex: "^\\d{9}$" },
    { countryId: "BR", countryName: "Brazil", countryCode: "+55", regex: "^\\d{11}$" },
    { countryId: "CA", countryName: "Canada", countryCode: "+10", regex: "^\\d{10}$" },
    { countryId: "CN", countryName: "China", countryCode: "+86", regex: "^\\d{11}$" },
    { countryId: "FR", countryName: "France", countryCode: "+33", regex: "^\\d{9}$" },
    { countryId: "DE", countryName: "Germany", countryCode: "+49", regex: "^\\d{11}$" },
    { countryId: "IN", countryName: "India", countryCode: "+91", regex: "^[6-9]\\d{9}$" },
    { countryId: "ID", countryName: "Indonesia", countryCode: "+62", regex: "^\\d{10,12}$" },
    { countryId: "IT", countryName: "Italy", countryCode: "+39", regex: "^\\d{10}$" },
    { countryId: "JP", countryName: "Japan", countryCode: "+81", regex: "^\\d{10}$" },
    { countryId: "MX", countryName: "Mexico", countryCode: "+52", regex: "^\\d{10}$" },
    { countryId: "PK", countryName: "Pakistan", countryCode: "+92", regex: "^\\d{10}$" },
    { countryId: "RU", countryName: "Russia", countryCode: "+7", regex: "^\\d{10}$" },
    { countryId: "SA", countryName: "Saudi Arabia", countryCode: "+966", regex: "^\\d{9}$" },
    { countryId: "ZA", countryName: "South Africa", countryCode: "+27", regex: "^\\d{9}$" },
    { countryId: "ES", countryName: "Spain", countryCode: "+34", regex: "^\\d{9}$" },
    { countryId: "SE", countryName: "Sweden", countryCode: "+46", regex: "^\\d{9}$" },
    { countryId: "CH", countryName: "Switzerland", countryCode: "+41", regex: "^\\d{9}$" },
    { countryId: "GB", countryName: "United Kingdom", countryCode: "+44", regex: "^(7\\d{9})$" },
    { countryId: "US", countryName: "United States", countryCode: "+1", regex: "^[2-9]\\d{2}[2-9]\\d{6}$" },
  ];
  